### ISSUE TITLE
net.appjet.bodylock.JSRuntimeException

### ISSUE THREAD

**Issue by nikosprodro** [hackpad/hackpad#45]
<a href="https://github.com/romeo0"><img src="https://avatars1.githubusercontent.com/u/16645530?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [romeo0](https://github.com/romeo0)**
_Sun Oct 23 14:41:44 2016_
_Originally opened as https://github.com/dropbox/hackpad/issues/64_

----

I meet a problem when I run  /hackpad-master/bin/run.js

Here is the error info:
`Startup execution failed with error.
net.appjet.bodylock.JSRuntimeException: Error: Neither module exists: etherpad.collab.ace.easysync2, etherpad.collab.ace.easysync2.{AttribPool,Changeset}
    at net.appjet.bodylock.BodyLock$.unwrapExceptionIfNecessary(bodylock.scala:160)
    at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:80)
    at net.appjet.oui.ScopeReuseManager$$anonfun$newRunner$1.apply$mcV$sp(servermodel.scala:127)
    at net.appjet.oui.ScopeReuseManager$$anonfun$newRunner$1.apply(servermodel.scala:123)
    at net.appjet.oui.ScopeReuseManager$$anonfun$newRunner$1.apply(servermodel.scala:123)
    at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
    at net.appjet.oui.ExecutionContextUtils$.withContext(execution.scala:340)
    at net.appjet.oui.ScopeReuseManager$.newRunner(servermodel.scala:123)
    at net.appjet.oui.ScopeReuseManager$$anonfun$getRunner$1.apply(servermodel.scala:149)
    at net.appjet.oui.ScopeReuseManager$$anonfun$getRunner$1.apply(servermodel.scala:139)
    at net.appjet.oui.ScopeReuseManager$.readLocked(servermodel.scala:86)
    at net.appjet.oui.ScopeReuseManager$.getRunner(servermodel.scala:139)
    at net.appjet.oui.execution$.runOutOfBand(execution.scala:614)
    at net.appjet.oui.main$.runOnStartup(main.scala:114)
    at net.appjet.oui.main$.main(main.scala:292)
    at net.appjet.oui.main.main(main.scala)
Caused by: org.mozilla.javascript.JavaScriptException: foo (module preamble.js#200)
    at JS$module$preamble$js$2._c_importPath_12(module preamble.js:200)
    at JS$module$preamble$js$2.call(module preamble.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
    at JS$module$preamble$js$2._c_anonymous_16(module preamble.js:233)
    at JS$module$preamble$js$2.call(module preamble.js)
    at org.mozilla.javascript.NativeArray.iterativeMethod(NativeArray.java:1563)
    at org.mozilla.javascript.NativeArray.execIdCall(NativeArray.java:345)
    at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:129)
    at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
    at JS$module$preamble$js$2._c_runScheduledImports_15(module preamble.js:232)
    at JS$module$preamble$js$2.call(module preamble.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
    at JS$module$preamble$js$2._c_anonymous_18(module preamble.js:272)
    at JS$module$preamble$js$2.call(module preamble.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
    at JS$module$postamble$js$253._c_script_0(module postamble.js:18)
    at JS$module$postamble$js$253.call(module postamble.js)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
    at JS$module$postamble$js$253.call(module postamble.js)
    at JS$module$postamble$js$253.exec(module postamble.js)
    at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:76)
    at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:75)
    at net.appjet.bodylock.BodyLock$.runInContext(bodylock.scala:111)
    at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:75)
    ... 14 more
`

I find some solution in etherpad, it tell me to Rebuild the ace dependency.
But how can I  do this work in hackpad?

**Comment by Auroch** [comment]
Same problem when trying to install Hackpad on Debian Stretch with Oracle JDK8, but Scala and other things from APT.
Doy you have a solution or search path to follow ?

**Comment by pors** [comment]
Did you follow the install instructions here to the letter? https://github.com/hackpad/hackpad/blob/master/INSTALL.md

BTW the latest version of Scala won't work. `brew install scala@2.11` should do it (on a Mac).

**Comment by Auroch** [comment]
Hi Mark @pors,
except the config for sending mail (temporarily) and the "Create an account in development" (because a have the error), I think that a i have correctly followed the installation procedure.
Another major source of error is perhaps the Oracle JDK8, no more possible for me to download the JDK7.
Do you think it's a scala type of error ? As mentioned, I'm on Debian Stretch, not on Mac OS and my Scala version is the apt repository one (2.11.8-1) Do you think it's possibly linked to this version ?

**Comment by pors** [comment]
Ah, JDK8 is not backward compatible, and hackpad won't work with it.
