### ISSUE TITLE
Switching between workspaces doesn't work

### ISSUE THREAD

**Issue by erwblo** [hackpad/hackpad#78]
When I switch between workspaces I get: 
net.appjet.bodylock.JSRuntimeException: Error while executing: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:84)
	at net.appjet.oui.execution$$anonfun$execute$4.apply(execution.scala:517)
	at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
	at net.appjet.oui.ExecutionContextUtils$.withContext(execution.scala:340)
	at net.appjet.oui.execution$.execute(execution.scala:513)
	at net.appjet.oui.execution$.execute(execution.scala:492)
	at net.appjet.oui.OuiServlet.execute(execution.scala:422)
	at net.appjet.oui.OuiServlet.doGet(execution.scala:366)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
	at org.mortbay.jetty.servlet.S

**Comment by pors** [comment]
This is caused by not having a wildcard SSL certificate set up. Not a bug.
