### ISSUE TITLE
EXCEPTION occurred when opened the hackpad home page  

### ISSUE THREAD

**Issue by phelixzh** [hackpad/hackpad#82]
Hi everyone, 
I installed the hackpad following INSTALL.md， but I got an EXCEPTION when accessing http://localhost:9000  in my browser.

Ubuntu 16.04, Java 7u80 , scala 2.11.6, mysql 5.7

Here is the EXCEPTION :
```
exception: 	get	/	http	bd87825416ff4961	200	net.appjet.bodylock.JSRuntimeException: Error: Invalid redirect: undefined
exception: 	at net.appjet.bodylock.BodyLock$.unwrapExceptionIfNecessary(bodylock.scala:160)
exception: 	at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:80)
exception: 	at net.appjet.oui.execution$$anonfun$execute$4.apply(execution.scala:517)
exception: 	at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
exception: 	at net.appjet.oui.ExecutionContextUtils$.withContext(execution.scala:340)
exception: 	at net.appjet.oui.execution$.execute(execution.scala:513)
exception: 	at net.appjet.oui.execution$.execute(execution.scala:492)
exception: 	at net.appjet.oui.OuiServlet.execute(execution.scala:422)
exception: 	at net.appjet.oui.OuiServlet.doGet(execution.scala:366)
exception: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
exception: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
exception: 	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
exception: 	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
exception: 	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
exception: 	at org.mortbay.jetty.handler.HandlerList.handle(HandlerList.java:49)
exception: 	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
exception: 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
exception: 	at org.mortbay.jetty.Server.handle(Server.java:322)
exception: 	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:536)
exception: 	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:913)
exception: 	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:539)
exception: 	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
exception: 	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:405)
exception: 	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
exception: 	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
exception: Caused by: org.mozilla.javascript.JavaScriptException: foo (module global/response.js#106)
exception: 	at JS$module$global$response$js$139._c_anonymous_8(module global/response.js:106)
exception: 	at JS$module$global$response$js$139.call(module global/response.js)
exception: 	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
exception: 	at JS$module$etherpad$control$maincontrol$js$230._c_render_main_get_1(module etherpad/control/maincontrol.js:94)
exception: 	at JS$module$etherpad$control$maincontrol$js$230.call(module etherpad/control/maincontrol.js)
exception: 	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2521)
exception: 	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:300)
exception: 	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:129)
exception: 	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
exception: 	at JS$module$dispatch$js$46._c_anonymous_9(module dispatch.js:122)
exception: 	at JS$module$dispatch$js$46.call(module dispatch.js)
exception: 	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
exception: 	at JS$module$main$js$140._c_handlePath_26(module main.js:450)
exception: 	at JS$module$main$js$140.call(module main.js)
exception: 	at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
exception: 	at JS$module$main$js$140._c_anonymous_8(module main.js:180)
exception: 	at JS$module$main$js$140.call(module main.js)
exception: 	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
exception: 	at JS$module$onrequest$js$263._c_script_0(module onrequest.js:24)
exception: 	at JS$module$onrequest$js$263.call(module onrequest.js)
exception: 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
exception: 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
exception: 	at JS$module$onrequest$js$263.call(module onrequest.js)
exception: 	at JS$module$onrequest$js$263.exec(module onrequest.js)
exception: 	at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:76)
exception: 	at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:75)
exception: 	at net.appjet.bodylock.BodyLock$.runInContext(bodylock.scala:111)
exception: 	at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:75)
exception: 	... 23 more
exception: 	a6f650b791ef0cb9	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36

```
Please help me to solve this problem,  thx a lot.

**Comment by cantillon1** [comment]
Had the same problem, I believe the root cause is in etherpad/src/etherpad/control/maincontrol.js: 

```
  if(appjet.config['REDIRECT_HOME_TO'] !== 'false' && appjet.config['REDIRECT_HOME_TO'] !== '__redirect_to_home__') {
      response.redirect(appjet.config['REDIRECT_HOME_TO']);
```

Setting REDIRECT_HOME_TO in etherpad.local.properties resolved this for me

**Comment by cantillon1** [comment]
Had the same problem, root cause seemed to be in etherpad/src/etherpad/control/maincontrol.js:

```
  if(appjet.config['REDIRECT_HOME_TO'] !== 'false' && appjet.config['REDIRECT_HOME_TO'] !== '__redirect_to_home__') {
      response.redirect(appjet.config['REDIRECT_HOME_TO']);
  }
```

I resolved this by setting the following in the etherpad.local.properties config file: 

`REDIRECT_HOME_TO = false`
